# -*- coding: utf-8 -*-
"""Plant Disease Classification with Visual Analysis (university project)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DF4upnRsBcyJyzneQGfwpKgM1K7Dh6LH

# New section
"""

!pip install kaggle

!kaggle datasets download -d emmarex/plantdisease
!unzip plantdisease.zip

# ============================================
# Deep Learning-based Plant Disease Classification
# ============================================

# 1. Import Libraries
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
import matplotlib.pyplot as plt
import numpy as np
import os

# ============================================
# 2. Dataset Preparation
# ============================================

# Dataset Path
dataset_path = "PlantVillage"

# ============================================
# 3. Count Healthy & Diseased Images
# ============================================

healthy_count = 0
disease_count = 0

# Loop through dataset folders
for folder in os.listdir(dataset_path):

    folder_path = os.path.join(dataset_path, folder)

    # Count image files
    image_count = len(os.listdir(folder_path))

    # Check Healthy or Diseased
    if "healthy" in folder.lower():
        healthy_count += image_count
    else:
        disease_count += image_count

# Total Images
total_images = healthy_count + disease_count

# Percentage Calculation
healthy_percentage = (healthy_count / total_images) * 100
disease_percentage = (disease_count / total_images) * 100

# Print Results
print("===================================")
print("Dataset Information")
print("===================================")

print(f"Total Images: {total_images}")

print(f"Healthy Leaf Images: {healthy_count}")
print(f"Healthy Percentage: {healthy_percentage:.2f}%")

print(f"Diseased Leaf Images: {disease_count}")
print(f"Diseased Percentage: {disease_percentage:.2f}%")

# ============================================
# 4. Image Data Generator
# ============================================

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

# Training Data
train_data = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(128, 128),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

# Validation Data
validation_data = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(128, 128),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

# ============================================
# 5. Load Pretrained Model
# ============================================

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(128, 128, 3)
)

# Freeze pretrained layers
base_model.trainable = False

# ============================================
# 6. Build Deep Learning Model
# ============================================

model = Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(128, activation='relu'),
    Dense(train_data.num_classes, activation='softmax')
])

# ============================================
# 7. Compile Model
# ============================================

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# ============================================
# 8. Train Model
# ============================================

history = model.fit(
    train_data,
    validation_data=validation_data,
    epochs=5
)

# ============================================
# 9. Accuracy Graph
# ============================================

plt.figure(figsize=(8,5))

plt.plot(
    history.history['accuracy'],
    label='Training Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()

plt.show()

# ============================================
# 10. Loss Graph
# ============================================

plt.figure(figsize=(8,5))

plt.plot(
    history.history['loss'],
    label='Training Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.title("Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.show()

# 11. Test Prediction (Corrected)

from tensorflow.keras.preprocessing import image

# Dynamically find a test image from the dataset
test_image_found = False
img_path = ''
for class_folder in os.listdir(dataset_path):
    class_folder_path = os.path.join(dataset_path, class_folder)
    if os.path.isdir(class_folder_path):
        images_in_folder = [f for f in os.listdir(class_folder_path) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp'))]
        if images_in_folder:
            img_path = os.path.join(class_folder_path, images_in_folder[0])
            test_image_found = True
            break

if not test_image_found:
    raise FileNotFoundError("No image found in the dataset for testing. Please ensure the 'PlantVillage' directory contains image files.")

print(f"Using test image: {img_path}")

# Display the chosen test image
plt.figure(figsize=(6,6))
plt.imshow(plt.imread(img_path))
plt.title(f"Test Image: {os.path.basename(img_path)}")
plt.axis('off')
plt.show()

# Load image
img = image.load_img(
    img_path,
    target_size=(128, 128)
)

# Convert image to array
img_array = image.img_to_array(img)

# Normalize image
img_array = img_array / 255.0

# Expand dimensions
img_array = np.expand_dims(img_array, axis=0)

# Prediction
prediction = model.predict(img_array)

# Class Names
class_names = list(train_data.class_indices.keys())

# Final Output
predicted_class = class_names[np.argmax(prediction)]

print("===================================")
print("Prediction Result")
print("===================================")

print("Predicted Disease:", predicted_class)